general {
    col.active_border = rgba(AA8353ff) rgba(5B4D35ff) 45deg
    col.inactive_border = rgba(413D35ff) rgba(7E7734ff) 45deg
}

group {
    col.border_active = rgba(413D35ff) rgba(7E7734ff) 45deg
    col.border_inactive = rgba(464439cc) rgba(536532cc) 45deg
    col.border_locked_active = rgba(534C37ff) rgba(675F36ff) 45deg
    col.border_locked_inactive = rgba(505038cc) rgba(545A35cc) 45deg
}
